error
Traceback (most recent call last):
  File "/home/pbrlionocde/projects/home/tst_okx/api_wrappers/okx.py", line 55, in execute_request
    response = requests.request(**request_params)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/v5/account/balance': No scheme supplied. Perhaps you meant http:///api/v5/account/balance?
2022-11-13 18:07:35,857 - error_logger - ERROR - error
Traceback (most recent call last):
  File "/home/pbrlionocde/projects/home/tst_okx/api_wrappers/okx.py", line 62, in execute_request
    response = requests.request(**request_params)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3.10/site-packages/requests/utils.py", line 1037, in check_header_validity
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part (1) from {'x-simulated-trading': 1} must be of type str or bytes, not <class 'int'>
2022-11-14 15:11:00,596 - error_logger - ERROR - error
Traceback (most recent call last):
  File "/home/user/projects/tst/tst_okx/api_wrappers/okx.py", line 63, in execute_request
    response = requests.request(self.get_request_kwargs(
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 25, in get_request_kwargs
    request_params = self.__process_arguments()
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 39, in __process_arguments
    handler(request_params=request_params)
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 45, in _url
    request_params['url']=f'{self.domain}{self.kwargs["url"]}'
AttributeError: 'OkxClient' object has no attribute 'domain'
2022-11-14 15:11:30,536 - error_logger - ERROR - error
Traceback (most recent call last):
  File "/home/user/projects/tst/tst_okx/api_wrappers/okx.py", line 63, in execute_request
    response = requests.request(self.get_request_kwargs(
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 25, in get_request_kwargs
    request_params = self.__process_arguments()
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 39, in __process_arguments
    handler(request_params=request_params)
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 45, in _url
    request_params['url']=f'{self.domain}{self.kwargs["url"]}'
AttributeError: 'OkxClient' object has no attribute 'domain'
2022-11-14 15:49:12,581 - error_logger - ERROR - error
Traceback (most recent call last):
  File "/home/user/projects/tst/tst_okx/api_wrappers/okx.py", line 63, in execute_request
    response = requests.request(self.get_request_kwargs(
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 25, in get_request_kwargs
    request_params = self.__process_arguments()
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 39, in __process_arguments
    handler(request_params=request_params)
  File "/home/user/projects/tst/tst_okx/api_wrappers/requests_utilities.py", line 45, in _url
    request_params['url']=f'{self.domain}{self.kwargs["url"]}'
AttributeError: 'OkxClient' object has no attribute 'domain'
2022-11-14 15:57:21,450 - error_logger - ERROR - error
Traceback (most recent call last):
  File "/home/user/projects/tst/tst_okx/api_wrappers/okx.py", line 72, in execute_request
    response = requests.request(request_params)
TypeError: request() missing 1 required positional argument: 'url'
